$schema: https://rocket-hangar.github.io/rocket-punch/schemas/packages.json
'@anchor-protocol/*':
  version: 0.10.0
  tag: latest
'@terra-money/*':
  version: 0.11.1
  tag: latest
'@terra-dev/*':
  version: 0.11.0
  tag: latest